<?php
// Protected Media Links (PML) Class Map - Auto-generated by build/generate-pml-class-map.php
// Plugin: Protected Media Links
// Do not edit this file manually.

return [
	'PML_Bot_Detector' => __DIR__ . '/utilities/bot-detector.php',
	'PML_Core' => __DIR__ . '/class-core.php',
	'PML_File_Handler' => __DIR__ . '/class-file-handler.php',
	'PML_Headless_Auth' => __DIR__ . '/class-pml-headless-auth.php',
	'PML_Install' => __DIR__ . '/class-install.php',
	'PML_Media_Library_Integration' => __DIR__ . '/class-media-library-integration.php',
	'PML_Media_Meta' => __DIR__ . '/class-media-meta.php',
	'PML_Settings' => __DIR__ . '/class-settings.php',
	'PML_Shortcodes' => __DIR__ . '/class-shortcodes.php',
	'PML_Token_Manager' => __DIR__ . '/class-token-manager.php',
	'PML_Token_Meta_Box' => __DIR__ . '/class-token-meta-box.php',
	'PML_User_List_Actions' => __DIR__ . '/class-user-list-actions.php',
];
